encass-policy:
  policy: "gateway-solution/encass-policy.xml"
  arguments:
  - name: "hello"
    type: "string"
  - name: "hello-again"
    type: "message"
  results:
  - name: "goodbye"
    type: "string"
  - name: "goodbye-again"
    type: "message"
encass-policy2:
  policy: "gateway-solution/encass-policy.xml"
  arguments:
  - name: "hello"
    type: "string"
  - name: "hello-again"
    type: "message"
  results:
  - name: "goodbye"
    type: "string"
  - name: "goodbye-again"
    type: "message"
