gateway-solution/v2/api2:
  url: "/example2"
  policy: "gateway-solution/another-service.xml"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties:
    ENV.k2:
gateway-solution/v1/api1:
  url: "/example"
  policy: "gateway-solution/another-service.xml"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties:
    ENV.k1:
gateway-solution/another-service:
  url: "/another-service-example"
  policy: "gateway-solution/another-service.xml"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
